### ISSUE TITLE
Prepare Code To Use Different PC for Driver Station

### ISSUE THREAD

**Issue by markpowers** [poly-rabbotics/2019-Deep-Space#3]
We are setting up one of the beefier Dell laptops (#3) to have the driver station software. Presumably the port mappings for USB devices could be different than the original driver station. I think we'd want a way to tell the code which laptop is driving and map the ports to commands appropriately.

**Comment by jordan-powers** [comment]
Port mappings are configurable in the USB tab of the DS

**Comment by markpowers** [comment]
Cool. So, a non-issue from a rookie. Closing.
